@startuml locadora

abstract class Extrato {
    + final String gerarExtrato(Cliente cliente)
    - formatarCorpoComBaseNosAlugueis(List<Aluguel> alugueis, String fimDeLinha)
    + {abstract} String formatarCabecalho(String fimDeLinha, String nomeCliente)
    + {abstract} String formatarCorpo(String fimDeLinha, Aluguel aluguel)
    + {abstract} String formatarRodape(String fimDeLinha, Cliente cliente)

}

class ExtratoHTML {
    
    + String formatarCabecalho(String fimDeLinha, String nomeCliente)
    + String formatarCorpo(String fimDeLinha, Aluguel aluguel)
    + String formatarRodape(String fimDeLinha, Cliente cliente)
}

class ExtratoTextoPuro {

    + String formatarCabecalho(String fimDeLinha, String nomeCliente)
    + String formatarCorpo(String fimDeLinha, Aluguel aluguel)
    + String formatarRodape(String fimDeLinha, Cliente cliente)
}

class Cliente { }

class ExtratoHTML extends Extrato
class ExtratoTextoPuro extends Extrato

Cliente .. Extrato : Usa

@enduml